= Wyn K Heng - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: Bluebird

Bluebird is a desktop based organisational tool for the working parent on the go. Bluebird is suitable
for a variety of day-to-day management tasks, including managing appointments for both yourself and your
child, and also organising the contact information from your Address Book. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 15 kLoC. +


This project portfolio serves to provide an insight into how Wyn K Heng has contributed to project Bluebird. Included
in this portfolio are the enhancements, features, tests and proposed enhancements that Wyn K Heng has contribued to the project.

*Code contributed*: [[https://github.com/CS2103AUG2017-T15-B4/main/blob/master/collated/main/wynkheng.md[Functional code]] [https://github.com/CS2103AUG2017-T15-B4/main/blob/master/collated/test/wynkheng.md[Test code]]

=== Enhancement Added: Hide/Unhide

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=hide]
include::../UserGuide.adoc[tag=unhide]

#End of Extract#

---

==== Justification

Since this application is directed largely at working parents who occasionally allow their children to explore the
the application, there might be contacts in Bluebird's address book that the parent might not want the child to see.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=hide]
include::../DeveloperGuide.adoc[tag=unhide]

#End of Extract#

---

=== Enhancement Added: Birthday Field

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=add]

#End of Extract#

---

==== Justification

Added a birthday field as an attribute so that users can now add birthday information to existing contacts' information
in their Bluebird address book.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=add]

#End of Extract#

---

=== Enhancement Added: Show Birthdays

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=showbirthdays]

#End of Extract#

---

==== Justification

Allows the user to see the birthdays of contacts in his Bluebird address book that are on the current day. 

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=showbirthdays]

#End of Extract#

---

=== Enhancement Proposed: Hide/Unhide tasks

Similar to having hide/unhide for person contacts, having hide/unhide for tasks would allow parent users to conceal
tasks that they wouldn't want their child to see. For example, doctor appointments or other sensitive tasks.

=== Enhancement Proposal: Show Birthday

To further upgrade the `showbirthdays` command, create a setting for `showbirthdays` such that the user can set the upper
and lower bounds for the birthdays to be shown. For example, the user could set `showbirthdays` command to show the
upcoming birthdays of contact(s) in Bluebird's address book for current day, 2 days, week, or month, subject to
their preference.

=== Other contributions

* Continually updated User Guide formatting, language and content throughout the course of the project (Pull requests https://github.com/CS2103AUG2017-T15-B4/main/pull/286, https://github.com/CS2103AUG2017-T15-B4/main/pull/185, https://github.com/CS2103AUG2017-T15-B4/main/pull/145, https://github.com/CS2103AUG2017-T15-B4/main/pull/106)
* Continually updated Developer Guide formatting, language and content throughout the course of the project. (Pull requests https://github.com/CS2103AUG2017-T15-B4/main/pull/90, https://github.com/CS2103AUG2017-T15-B4/main/pull/177, https://github.com/CS2103AUG2017-T15-B4/main/pull/183, https://github.com/CS2103AUG2017-T15-B4/main/pull/278)
